# Generated by Django 6.1.1 on 2026-09-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
